### ISSUE TITLE
Exchange 2019?

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/SCCMDocs.de-de#4]
Is Exchange 2019 supported or not?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f86d400f-d2a6-d50b-8d1f-18893af56d67
* Version Independent ID: 793a7196-8549-329c-bad5-c6b33f466ae7
* Content: [Unterstützte Clients und Geräte - Configuration Manager](https://docs.microsoft.com/de-de/configmgr/core/plan-design/configs/supported-operating-systems-for-clients-and-devices)
* Content Source: [sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md](https://github.com/Microsoft/SCCMDocs.de-de/blob/live/sccm/core/plan-design/configs/supported-operating-systems-for-clients-and-devices.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by srvbpigh** [comment]
Hello, @trudolf-msft
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @trudolf-msft, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/SCCMdocs/issues/2283. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
